apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: dev
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      nodeSelector: 
        size: large


# kubectl label nodes <node-name> <label-key>=<label-value>
# kubectl label nodes kube-master size=large   --adding label to nodes

# kubectl label nodes kube-master size-        --deleting label from nodes

