apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: dev
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In # NotIn, Exists and DoesNotExist
                values:
                - large
                - medium

    # operator: In # or NotIn ==> key=value should be together.                      
    # operator: Exists or DoesNotExist ==> Only "key" is enough.


# kubectl label nodes <node-name> <label-key>=<label-value>
# kubectl label nodes kube-master size=large   --adding label to nodes

# kubectl label nodes kube-master size-   --deleting label from nodes



# - There are currently three types of node affinity:

#   - requiredDuringSchedulingIgnoredDuringExecution
#   - preferredDuringSchedulingIgnoredDuringExecution
#   - requiredDuringSchedulingRequiredDuringExecution